version: '2'

services:
  spm-client:
   image: sematext/spm-client:1.31.100
   hostname: spm-client-mongo
   privileged: true
   volumes: 
    # upcoming release will require access to docker socket, not req. for current 1.31.100
    - /var/run/docker.sock:/var/run/docker.sock
   environment:
    # token mongodb mongo-url
    - SPM_CONFIG=${SPM_TOKEN} mongodb mongodb://mongodb:27017/admin
   links: 
    - mongodb

  mongodb:
   image: mongo:latest
   ports:
    - "27017:27017"


  
